name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: sariftachamo-9
          outputs: |
            output/snake.svg
            output/snake-dark.svg?palette=github-dark
      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mkdir -p output
          git add output/
          git diff --staged --quiet || git commit -m "Update snake animation"
          git push
